### ISSUE TITLE
Product Functionality

### ISSUE THREAD

**Issue by thayanithi-picco** [spurtcms/spurtcms#33]
While creating a new product ,error occurred while try to upload the image in media folder.

**Comment by ambiga-piccosoft** [comment]
Thank you for raise bug.Now resolved the bug
![Screenshot from 2024-06-11 16-16-45](https://github.com/spurtcms/spurtcms/assets/133978862/cc30a35b-aad4-4a97-8ede-c1dd6f63d071)

**Comment by thayanithi-picco** [comment]
Thanks Ambiga.This works like a charm
