### ISSUE TITLE
Product Filter Requirement

### ISSUE THREAD

**Issue by ambiga-piccosoft** [spurtcms/spurtcms#34]
In Ecommerce catelougue tab,it allows user to filter by product name and status of the product.If you could extend this to filter the products by price it would be helpful.

**Comment by nithya-picco** [comment]
Thanks for your suggestion. and now added your filter requirement.
![Uploading Screenshot from 2024-06-11 16-55-10.png…]()

**Comment by ambiga-piccosoft** [comment]
Thank you team.
