### ISSUE TITLE
Product requirement

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#35]
Stock related info need to be added while creating a new product.

**Comment by thayanithi-picco** [comment]
Thanks for your suggestion. Now we implemented
![Screenshot from 2024-06-11 16-24-42](https://github.com/spurtcms/spurtcms/assets/144322751/65167bf6-f266-40e1-893a-0054015e719f)

**Comment by nithya-picco** [comment]
Thank you for implementing the feature.Truly helpful.
