### ISSUE TITLE
Receive Notification by mail

### ISSUE THREAD

**Issue by ambiga-piccosoft** [spurtcms/spurtcms#37]
Allow the admin to select the user to whom the notifications to be send on email.Also allow multi select Functionality for the users in this feature.

**Comment by spurtcmsdeveloper-192** [comment]
Thanks for your suggestion will take this 
as an this feature request and 
update the status.

**Comment by spurtcmsdeveloper-192** [comment]
We are excited to share with you that we have implemented the new feature which you have requested which allows the application to send notification to multiple users.

![Screenshot from 2024-06-18 16-13-26](https://github.com/spurtcms/spurtcms/assets/169228281/851df41a-9293-4a15-a0bc-a51a4c554af2)

**Comment by ambiga-piccosoft** [comment]
Thank you.This feature is useful
