### ISSUE TITLE
Multiselect Status change functionality.

### ISSUE THREAD

**Issue by thayanithi-picco** [spurtcms/spurtcms#38]
Currently system allows the user to select single entry for status change functionality. Can you provide a multiselect status change functionality on all list pages to ease the monotonous task of user?

**Comment by ambiga-piccosoft** [comment]
Thanks for suggesting this feature.Will implement this in our application shortly

**Comment by ambiga-piccosoft** [comment]
This feature was implemented in all list pages.
![Screenshot from 2024-06-18 16-07-23](https://github.com/spurtcms/spurtcms/assets/133978862/d066de2c-f516-442a-80ae-71ef9256177b)
![Screenshot from 2024-06-18 16-08-36](https://github.com/spurtcms/spurtcms/assets/133978862/08e75382-c288-4922-8b64-c5e768a73312)

**Comment by thayanithi-picco** [comment]
Thank you for implementing the feature. Truly helpful
