### ISSUE TITLE
Search input Requirement

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#39]
Could you implement the shortcut key for search as (ctrl+/) throughout the application.This feature would be user friendly for all.

**Comment by ambiga-piccosoft** [comment]
Thank You So much for your query, we really appreciate your contribution towards spurtcms. We will take up This feature request shortly.

**Comment by ambiga-piccosoft** [comment]
This feature was implemented in all list pages.

**Comment by nithya-picco** [comment]
Thank you for implementing the feature.Truly helpful.
