### ISSUE TITLE
Pagination Requirement

### ISSUE THREAD

**Issue by spurtcmsdeveloper-146** [spurtcms/spurtcms#40]
Currently, updating the user details and saving the page is routed to the member's home page. If I have to update
 the member on a different page it should reflect on the same page.

**Comment by spurtcmsdeveloper-73** [comment]
Thanks for your suggestion we will take up this feature request shortly.

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for bringing this to our attention. Now members can update their details seamlessly, and changes reflect on the same page without redirecting to the home page.

**Comment by spurtcmsdeveloper-146** [comment]
Thank you for implementing the feature.
