### ISSUE TITLE
Applicants Multiple Select Checkbox

### ISSUE THREAD

**Issue by spurtcmsdeveloper-192** [spurtcms/spurtcms#41]
Unable to update the status of multiple customers who are currently active to inactive.

**Comment by nithya-picco** [comment]
Hi @spurtcmsdeveloper-192 ,we will check that above issue. and will fix the issue shortly.

**Comment by nithya-picco** [comment]
I happy to say that  above issue was fixed. Please check this.

**Comment by ambiga-piccosoft** [comment]
Thank you.This feature is useful
