### ISSUE TITLE
Status colour code

### ISSUE THREAD

**Issue by ambiga-piccosoft** [spurtcms/spurtcms#42]
Could you provide a colour code for order status , it’s very useful for differences the another order status .

**Comment by spurtcmsdeveloper-73** [comment]
Thanks for your suggestion; this feature will be implemented in our application shortly.

**Comment by spurtcmsdeveloper-73** [comment]
we have resolved the need for a color code to distinguish between different order statuses, which will greatly enhance clarity.
![Screenshot (8)](https://github.com/spurtcms/spurtcms/assets/172354297/7a4d028b-33ed-4851-857e-5ddb29a323b1)

**Comment by ambiga-piccosoft** [comment]
Thank you for implementing the feature.Truly helpful
