### ISSUE TITLE
Customer Create functionality

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#43]
While creating a customer couldn’t upload profile image

**Comment by ambiga-piccosoft** [comment]
Hi @spurtcmsdeveloper-73 ,we will fix the issues shortly.

**Comment by ambiga-piccosoft** [comment]
Now Implemented customer profile upload.
![Screenshot from 2024-06-22 16-20-24](https://github.com/spurtcms/spurtcms/assets/133978862/61d69495-6d4b-4896-94ef-1bf36acc3f80)

**Comment by spurtcmsdeveloper-73** [comment]
Great to hear that the customer profile upload feature has been implemented! I look forward to trying it out. Thank you for the update!
