### ISSUE TITLE
Member Update Meta data not updated

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#44]
while update member meta info like title ,tag and description is not updated.

**Comment by nithya-picco** [comment]
Hello @spurtcmsdeveloper-73 , Thank you raising that issue.We will fix that issue shortly.

**Comment by nithya-picco** [comment]
Now this issue was fixed. Please Check this.
![Screenshot from 2024-06-22 16-07-48](https://github.com/spurtcms/spurtcms/assets/144322205/0104b5ce-922c-47f9-bb67-65a865713786)

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for letting me know that the issue with updating member meta info has been fixed.
