### ISSUE TITLE
Display stock details

### ISSUE THREAD

**Issue by ambiga-piccosoft** [spurtcms/spurtcms#45]
Please add field stock in product .

**Comment by spurtcmsdeveloper-73** [comment]
Thank You So much for your query, we really appreciate your contribution towards Spurt-cms. We will take up this feature request shortly.

**Comment by spurtcmsdeveloper-73** [comment]
we had implemented the stock field
![Screenshot (17)](https://github.com/spurtcms/spurtcms/assets/172354297/81d4decb-0679-4bd2-a2c9-a5c8ab4f76cf)

**Comment by ambiga-piccosoft** [comment]
Thank you.This feature is useful
