### ISSUE TITLE
Multiple options to payment

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#46]
Add Multiple option for to pay payment.

**Comment by ambiga-piccosoft** [comment]
Thanks for your suggestion.we will take this as an enhancement and update the status here.

**Comment by ambiga-piccosoft** [comment]
We have implemented multiple currency options for payment to enhance user convenience across different countries.
![Screenshot from 2024-07-09 10-12-57](https://github.com/spurtcms/spurtcms/assets/133978862/1c1ea04a-fb1c-47e3-83da-6f7b985caee0)

**Comment by nithya-picco** [comment]
Thank you for implementing the feature.Truly helpful
