### ISSUE TITLE
Jobs Pagination Requirement

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#47]
In Jobs list page all data shown in single page. Try to display standard number of data to  all pages using pagination

**Comment by thayanithi-picco** [comment]
I've implemented pagination on the Jobs list page so that now the data is displayed in standard numbers across multiple pages.

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for implementing pagination on the Jobs list page! I appreciate your efforts in improving the user experience.
