### ISSUE TITLE
E-Commerce customer requirement

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#49]
While creating a new customer data toggle button not reflecting try to resolve it.

**Comment by ambiga-piccosoft** [comment]
Thank you raising that issue.We will fix that issue  Shortly.

**Comment by ambiga-piccosoft** [comment]
Now, you should see the toggle button reflecting accurately during the creation process.

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for resolving the issue with the toggle button for new customer data. I appreciate your prompt attention to this.
