### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#50]
Data import functionality the channels list doesn't display all active channels.

**Comment by ambiga-piccosoft** [comment]
we will check that above issue and will fix the issue shortly.

**Comment by ambiga-piccosoft** [comment]
![Screenshot from 2024-07-06 11-20-10](https://github.com/spurtcms/spurtcms/assets/133978862/4c1cbd56-23b4-40f9-8c92-325a7a55bb8e)

**Comment by nithya-picco** [comment]
Thank you for fixing the above issue.
