### ISSUE TITLE
Customer multiple data delete

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#51]
Unable to delete multiple data in customers. please work on these functionality to resolve it.

**Comment by ambiga-piccosoft** [comment]
we will check that above issue and will fix the issue shortly.

**Comment by ambiga-piccosoft** [comment]
Regarding the request with deleting multiple customer data, I've successfully resolved the functionality.You should now be able to delete multiple customer records without any issue

**Comment by nithya-picco** [comment]
Thank you for implementing the feature.Truly helpful

**Comment by nithya-picco** [comment]
Thank you for implementing the feature.Truly helpful
