### ISSUE TITLE
Multiple currency for payments

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#52]
Please give multiple currency options for payment as its very useful for users across different countries.

**Comment by thayanithi-picco** [comment]
Thanks for your suggestion. We will implement shortly

**Comment by spurtcmsdeveloper-53** [comment]
I am pleased to inform you that this feature has been developed and is now available for use.
![Screenshot from 2024-07-22 10-32-37](https://github.com/user-attachments/assets/dfd4fd18-4e3c-4e7d-b09c-3cc096888a76)

**Comment by nithya-picco** [comment]
Thank you for implementing this feature. Appreciate your work.
