### ISSUE TITLE
Channels additional fields option not updated

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#53]
While creating a channel additional fields options value not updated for the mapped entries

**Comment by ambiga-piccosoft** [comment]
Thank you for raised the issue, we will fix the issue shortly.

**Comment by ambiga-piccosoft** [comment]
Now fix the issuse . 
![Screenshot from 2024-07-09 10-37-28](https://github.com/spurtcms/spurtcms/assets/133978862/569d7189-1056-4b02-b5a2-c2eddf47ffd9)

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for addressing the issue with the additional fields for mapped entries. I appreciate the quick fix.
