### ISSUE TITLE
Member group delete functionality

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#54]
While deleting the member group ,the members reference were still mapped to the same group. That particular member group 
were not moved to default group.Could you look into this?

**Comment by thayanithi-picco** [comment]
Thank you for bringing this to our attention. we will fix the issues shortly

**Comment by thayanithi-picco** [comment]
Regarding the issue with deleting multiple customer data, I've successfully resolved the functionality. You should now be able to delete multiple customer records without any issue.

**Comment by nithya-picco** [comment]
Thank you for implementing the feature.Truly helpful.

**Comment by nithya-picco** [comment]
Thank you for implementing the feature.Truly helpful.
