### ISSUE TITLE
Channels based entry count issues

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#55]
channel entries count miss match in channel list page

**Comment by ambiga-piccosoft** [comment]
Now fix the channel entries count .
![Screenshot from 2024-07-09 10-32-05](https://github.com/spurtcms/spurtcms/assets/133978862/28fd4a99-388c-4f9c-aaa1-c922ec0d9768)

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for fixing the channel entries count issue! I appreciate your prompt response.
