### ISSUE TITLE
Email Title Editable

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#56]
currently in email template section mail body and the subjects are editable.An option should be there to edit the mail title would be helpful.

**Comment by spurtcmsdeveloper-53** [comment]
This requirement was Implemented.
![Screenshot from 2024-07-20 09-43-06](https://github.com/user-attachments/assets/db0af665-aefe-4913-bd6b-40e5792faa91)

**Comment by nithya-picco** [comment]
Thank you.This feature is useful.

**Comment by nithya-picco** [comment]
Thank you.This feature is useful
