### ISSUE TITLE
Add to Cart

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#59]
Add to Cart functionality throws an internal server error.could you please Look into this?

**Comment by spurtcmsdeveloper-53** [comment]
Now fixed the issue.successfully added the product in cart.
![Screenshot from 2024-07-23 10-54-29](https://github.com/user-attachments/assets/dc21fbf3-4515-4891-8a38-9d7785c58265)

**Comment by nithya-picco** [comment]
Thank you for fixing this issue. It is now working fine.
