### ISSUE TITLE
one product more than one category

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#60]
If I add a product I choose multiple categories the category based product list is not working as expected. could you fix this?

**Comment by thayanithi-picco** [comment]
Thank you for raised the issue, we will fix the issue shortly.

**Comment by spurtcmsdeveloper-53** [comment]
I am pleased to inform you that this issue has been fixed and is now available for use.

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for addressing the issue. I appreciate your prompt attention to this matter.
