### ISSUE TITLE
Media modal scroll issue

### ISSUE THREAD

**Issue by spurtcmsdeveloper-73** [spurtcms/spurtcms#61]
when I scroll the media ,modal media images are empty while scrolling.

**Comment by thayanithi-picco** [comment]
Thank you for raised the issue, we will fix the issue shortly.

**Comment by spurtcmsdeveloper-53** [comment]
The media scroll issue was implemented , please check and let us know your comments.
![Screenshot from 2024-07-23 10-13-57](https://github.com/user-attachments/assets/4398f067-8e39-4c33-8424-5b0c0ad7ab4b)

**Comment by spurtcmsdeveloper-73** [comment]
Thank you for addressing the media scroll issue.
