### ISSUE TITLE
Job Info filter requirement

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#62]
In job info please add a  filter functionality as its very usefull to filter applicants.

**Comment by thayanithi-picco** [comment]
Thanks for suggesting this feature. Will implement this in our application shortly

**Comment by spurtcmsdeveloper-53** [comment]
I'm happy to inform you that I have implemented this feature.
![Screenshot from 2024-07-22 10-55-26](https://github.com/user-attachments/assets/daf2e17b-f90f-4ad8-ae67-ba2677d1fcf6)

**Comment by nithya-picco** [comment]
Thank you

**Comment by nithya-picco** [comment]
Thank you for implementing this feature.It is very useful.
