### ISSUE TITLE
Preview Blocks

### ISSUE THREAD

**Issue by spurtcmsdeveloper-53** [spurtcms/spurtcms#72]
We new implement the preview concept in block.
![Screenshot from 2024-09-09 18-21-15](https://github.com/user-attachments/assets/66418513-734e-42aa-8cd9-59d37d3ed99f)

**Comment by spurtcmsdeveloper-73** [comment]
Implementing the preview concept in block is a fantastic development! It’s exciting to see how this feature will enhance our user experience by allowing us to see and interact with content before finalizing it.

**Comment by spurtcmsdeveloper-53** [comment]
Thank you for your response I'm looking forward to seeing how it enhances our  user experience by allowing us to interact with  content before finalizing it.
