### ISSUE TITLE
Image upload 

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#82]
The upload section of category image should restrict access to unsupported File types, such as word,pdf,ppt etc

**Comment by spurtcmsdeveloper-73** [comment]
The issue with the upload section has been resolved, restricting unsupported file types like Word, PDF, and PPT. Users will now receive notifications when attempting to upload incompatible formats.
![Screenshot (145)](https://github.com/user-attachments/assets/49786b9f-fb62-4dd4-86cd-2f9e3ba5b103)

**Comment by nithya-picco** [comment]
Thank you for fixing the issue.
