### ISSUE TITLE
Member Restrict

### ISSUE THREAD

**Issue by nithya-picco** [spurtcms/spurtcms#83]
While editing, the tick marks for the selected entries are not retained properly in the 'Member restrict' field

**Comment by spurtcmsdeveloper-73** [comment]
The issue with tick marks not being retained properly in the 'Member restrict' field has been identified and fixed. Please verify if the changes resolve the problem on your end. Thank you for raising this issue.

**Comment by nithya-picco** [comment]
Thank you for fixing this issue. It is now working fine.
